print("\n\t Features of PYTHON")
print("\n1.  Simple and Easy to Learn")
print("2.  Free ware and Open source")
print("3.  High Level Programming Language")
print("4.  Platform Independent")
print("5.  Portability")
print("6.  Dynamically Typed")
print("7.  Both Procedure Oriented and Object Orietend")
print("8.  Interpreted")
print("9.  Extensible")
print("10. Embedded")
print("11. Extensive Library")
